import os

base_dir = r"c:\Users\danie\Documents\Proyectos\proxvell_app\lib"

directories = [
    "core/router",
    "core/theme",
    "core/constants",
    "core/utils",
    "core/widgets/buttons",
    "core/widgets/cards",
    "core/widgets/chips",
    "core/widgets/inputs",
    "core/widgets/navigation",
    "core/widgets/states",
    "models",
    "controllers",
    "integration/api",
    "integration/services",
    "integration/mock",
    "integration/local",
    "views/intro",
    "views/auth",
    "views/onboarding",
    "views/main",
    "views/home",
    "views/for_you",
    "views/search",
    "views/destination",
    "views/favorites",
    "views/routes",
    "views/profile",
    "views/feedback",
]

files = [
    "main.dart",
    "app.dart",
    "core/router/app_router.dart",
    "core/theme/app_colors.dart",
    "core/theme/app_text_styles.dart",
    "core/theme/app_theme.dart",
    "core/constants/app_constants.dart",
    "core/utils/validators.dart",
    "core/widgets/buttons/proxvel_button.dart",
    "core/widgets/cards/destination_card.dart",
    "core/widgets/cards/destination_recommendation_card.dart",
    "core/widgets/chips/aspect_chip.dart",
    "core/widgets/inputs/proxvel_text_field.dart",
    "core/widgets/navigation/proxvel_bottom_navigation.dart",
    "core/widgets/states/loading_view.dart",
    "core/widgets/states/empty_view.dart",
    "core/widgets/states/error_view.dart",
    "models/user_model.dart",
    "models/traveler_profile_model.dart",
    "models/recommendation_request_model.dart",
    "models/recommendation_result_model.dart",
    "models/destination_model.dart",
    "models/aspect_score_model.dart",
    "models/explanation_model.dart",
    "models/context_signal_model.dart",
    "models/route_model.dart",
    "models/feedback_model.dart",
    "controllers/auth_controller.dart",
    "controllers/onboarding_controller.dart",
    "controllers/home_controller.dart",
    "controllers/search_controller.dart",
    "controllers/recommendation_controller.dart",
    "controllers/destination_controller.dart",
    "controllers/favorites_controller.dart",
    "controllers/routes_controller.dart",
    "controllers/profile_controller.dart",
    "controllers/feedback_controller.dart",
    "integration/api/api_client.dart",
    "integration/services/recommendation_service.dart",
    "integration/services/destination_service.dart",
    "integration/services/profile_service.dart",
    "integration/services/feedback_service.dart",
    "integration/services/route_service.dart",
    "integration/mock/mock_recommendation_data_source.dart",
    "integration/mock/mock_destination_data_source.dart",
    "integration/mock/mock_route_data_source.dart",
    "integration/local/local_storage_service.dart",
    "views/intro/intro_screen.dart",
    "views/auth/welcome_screen.dart",
    "views/auth/login_screen.dart",
    "views/auth/register_screen.dart",
    "views/onboarding/onboarding_profile_screen.dart",
    "views/main/main_layout.dart",
    "views/home/home_screen.dart",
    "views/for_you/for_you_screen.dart",
    "views/search/search_results_screen.dart",
    "views/destination/destination_detail_screen.dart",
    "views/favorites/favorites_screen.dart",
    "views/routes/routes_screen.dart",
    "views/profile/profile_screen.dart",
    "views/feedback/feedback_screen.dart",
]

for d in directories:
    os.makedirs(os.path.join(base_dir, d), exist_ok=True)

for f in files:
    file_path = os.path.join(base_dir, f)
    if not os.path.exists(file_path):
        with open(file_path, "w") as file:
            file.write("// TODO: Implement " + os.path.basename(f) + "\n")

print("Estructura creada.")
